// ------------ CSS ----------------
import "./globals.css";
// ------------ Types ----------------
import { ReactNode } from "react";
// ------------ Context ----------------
import { 
  AuthProvider,
  CartProvider, 
  OrdersProvider, 
  ThemeProvider 
} from "@/context";
// ------------ Components ----------------
import { Footer, Navbar } from "@/components/common";

export const metadata = {
  title: "CodeSphere Academy",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

// Define props for RootLayout
interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className='antialiased dark:bg-background-dark-secondary-color' >
        <ThemeProvider>
          <AuthProvider>
            <CartProvider>
              <OrdersProvider>
                <Navbar />
                {children}
                <Footer />
              </OrdersProvider>
            </CartProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
